---
name: xvfb_runner

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
 
    - name: prepare_stuff
      run: sudo apt-get -y install xvfb perl scrot inxi

    - name: inxi
      run: inxi -F && nproc

    - name: download
      run: wget -O /tmp/$$ http://intercity-vpn.de/minimoni.txt

    - name: minimoni
      run: ls -l /tmp/ && uname -a
